//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SplitLS2TP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SplitLS2TP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROGRAM RunSplitFiles
        ///	
        ///VAR 
        ///	Status					:INTEGER
        ///	prog_index				:INTEGER
        ///		ToolNumber: INTEGER
        ///		SpeedRPM:	INTEGER
        ///		CallProgName: STRING[20]
        ///	RetValueBool:BOOLEAN
        ///		
        ///
        ///-- Runs a TP Program
        ///ROUTINE runTP(FromDir,ProgName:STRING): INTEGER
        ///	VAR 
        ///		FromFullPathName :STRING[50]
        ///		ToFullPathName :STRING[50]
        ///		
        ///	BEGIN
        ///		
        ///		Status=0
        ///		prog_index=0
        ///		
        ///		FromFullPathName=FromDir+ProgName+&apos;.TP&apos;
        ///		ToFullPathName=&apos;MD:\&apos;+ProgName+&apos;.TP&apos;
        ///		WRITE TPDISPLAY (CR)		
        ///		WRITE TPDISPLAY (CR)
        ///		WRITE TPD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KL_Template_kl {
            get {
                return ResourceManager.GetString("KL_Template_kl", resourceCulture);
            }
        }
    }
}
